apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-challenge-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "devops-challenge-app.name" . }}
