name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./DevOpsChallengeApp/DevOpsChallengeApp.csproj

      - name: Build
        run: dotnet build ./DevOpsChallengeApp/DevOpsChallengeApp.csproj --configuration Release

      - name: Test
        run: dotnet test ./DevOpsChallengeApp/DevOpsChallengeApp.csproj || echo "No tests found"

      - name: Docker Build
        run: docker build -t devops-challenge-app ./DevOpsChallengeApp
